### ISSUE TITLE
Organise GitHub

### ISSUE THREAD

**Issue by AisanaZh177** [NeonNingen/GroupE_CW_Project#2]
Hey, people, could we spend 10 min organising GitHub a little?
I suggest we use branching to sort code into groups. For example, for the third version of the Front-end, I made a branch called "ProgSkeleton: Front-end".

I think it would make it quicker to find things. Let me know what you think and do correct me if I am doing smth wrong.

Cheers
AZ

**Comment by NeonNingen** [comment]
I will rework the github

**Comment by AisanaZh177** [comment]
Zain, it's nice you organised things, but do mind informing the team about it in the first place to avoid chaos. 
We still need to consider this matter once more to avoid people being lost on all the branches. For now, we can leave it how it is, but tomorrow we may need to re-adjust it one final time.

Regs
AZ
